name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: gialuong9820/mt7688-toolchain:v0.1.0

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo +nightly build -Z build-std --target=mipsel-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose
